# Generated by Django 2.2.5 on 2019-09-30 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='admin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=8)),
                ('email', models.CharField(max_length=50, null=True)),
                ('lasttime', models.DateTimeField(null=True)),
            ],
            options={
                'db_table': 'admin',
            },
        ),
        migrations.CreateModel(
            name='menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'menu',
            },
        ),
        migrations.CreateModel(
            name='news',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('catid', models.IntegerField(max_length=11)),
                ('title', models.CharField(max_length=30)),
                ('title_font_color', models.CharField(max_length=10)),
                ('thumb', models.CharField(max_length=30, null=True)),
                ('num', models.IntegerField(max_length=11)),
            ],
            options={
                'db_table': 'news',
            },
        ),
        migrations.CreateModel(
            name='news_content',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('newsid', models.IntegerField(max_length=11)),
                ('content', models.TextField()),
            ],
            options={
                'db_table': 'news_content',
            },
        ),
        migrations.CreateModel(
            name='position',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'position',
            },
        ),
        migrations.CreateModel(
            name='position_content',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('positionid', models.IntegerField(max_length=11)),
                ('newsid', models.IntegerField(max_length=11)),
            ],
            options={
                'db_table': 'position_content',
            },
        ),
    ]
