# Generated by Django 2.2.5 on 2019-09-30 02:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='registtime',
            field=models.DateTimeField(default=datetime.datetime(2019, 9, 30, 10, 20, 58, 228736)),
        ),
    ]
